### ISSUE TITLE
Secure HTTPS connection for Azure VM

### ISSUE THREAD

**Issue by masonlr** [alan-turing-institute/simulate#100]
## Acceptance criteria

- [x] Connection to Azure VM is over secure HTTPS connection

## Implementation notes

-  nginx API gateway can handle certificates

**Comment by masonlr** [comment]
Follow: https://certbot.eff.org/lets-encrypt/ubuntutrusty-nginx.html

i.e. for a `trusty` azure VM this corresponds to:

```
$ sudo apt-get update
$ sudo apt-get install software-properties-common
$ sudo add-apt-repository ppa:certbot/certbot
$ sudo apt-get update
$ sudo apt-get install python-certbot-nginx 
```


Kill all processes that are listening on port 80 and 443, find them using:

```
sudo netstat -antlp
```

Generate /etc/letsencrypt content

```
sudo certbot certonly --standalone -d simulate.uksouth.cloudapp.azure.com
```

**Comment by masonlr** [comment]
Open port 443 via the Azure portal:

![image](https://user-images.githubusercontent.com/5828176/45715598-85d5d880-bb8c-11e8-8eef-56d9ea0fad5f.png)

**Comment by masonlr** [comment]
Add a volume in the `docker-compose.production.json` file:

```yaml
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "5000:5000"
      - "5010:5010"
      - "5050:5050"
    networks:
      - share
    depends_on:
      - frontend
      - auth
      - middleware
      - manager
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
```
